spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/revenda
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  retry:
    instances:
      revendaPedido:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.lang.RuntimeException