spring:
  application:
    name: revenda-service
  datasource:
    url: jdbc:h2:mem:revenda-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true